from __future__ import annotations

import logging
import traceback

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from fastapi.staticfiles import StaticFiles
from starlette.middleware.base import BaseHTTPMiddleware

from app.api.v1.api import api_router
from app.core.config import settings
from app.core.database import engine
from app.models.base import Base
from app.services.document_processor import ensure_storage_dirs

logger = logging.getLogger("uvicorn.error")

app = FastAPI(title="テナントAIアシスタント API", version="1.0.0")


class CatchAllExceptionMiddleware(BaseHTTPMiddleware):
    """Catch unhandled exceptions and return JSON with CORS headers.

    Starlette's CORSMiddleware does not always add CORS headers to 500
    responses generated by the ASGI server.  This middleware converts
    unhandled exceptions into proper JSON responses *before* they
    escape the CORS layer.
    """

    async def dispatch(self, request: Request, call_next):
        try:
            return await call_next(request)
        except Exception as exc:
            logger.error(f"Unhandled exception: {type(exc).__name__}: {exc}")
            logger.error(traceback.format_exc())
            return JSONResponse(
                status_code=500,
                content={"detail": f"Internal server error: {type(exc).__name__}"},
            )


# Order matters: CatchAll runs inside CORS, so the JSON 500 response
# goes back through CORSMiddleware and gets CORS headers.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,  # Must be False when using "*"
    allow_methods=["*"],
    allow_headers=["*"],
)
app.add_middleware(CatchAllExceptionMiddleware)

# Static (only images)
# URL: /static/images/... -> storage/images/...
ensure_storage_dirs()
app.mount("/static/images", StaticFiles(directory=str(settings.images_dir)), name="images")


@app.on_event("startup")
async def on_startup() -> None:
    # Create tables (MVP: auto-create)
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)


app.include_router(api_router, prefix=settings.api_v1_prefix)


@app.get("/health")
async def health():
    return {"status": "ok"}


@app.get("/health/detail")
async def health_detail():
    """Detailed health check that tests API connectivity."""
    results = {
        "status": "ok",
        "gemini_api_key": "set" if settings.gemini_api_key else "MISSING",
        "openai_api_key": "set" if settings.openai_api_key else "MISSING",
        "gemini_chat_model": settings.gemini_chat_model,
        "gemini_chunk_model": settings.gemini_chunk_model,
        "storage_dir": str(settings.storage_dir),
        "storage_exists": settings.storage_dir.exists(),
        "cors_origins_raw": settings.cors_origins_raw,
        "backend_public_url": settings.backend_public_url,
    }

    # Test Gemini API
    try:
        from google import genai
        client = genai.Client(api_key=settings.gemini_api_key)
        response = await client.aio.models.generate_content(
            model=settings.gemini_chat_model,
            contents="Say 'ok' in one word.",
            config={"max_output_tokens": 5},
        )
        results["gemini_test"] = f"OK: {(response.text or '').strip()}"
    except Exception as e:
        results["gemini_test"] = f"FAILED: {type(e).__name__}: {e}"

    # Test OpenAI API (embeddings)
    try:
        from langchain_openai import OpenAIEmbeddings
        embeddings = OpenAIEmbeddings(model=settings.openai_embedding_model)
        await embeddings.aembed_query("test")
        results["openai_test"] = "OK"
    except Exception as e:
        results["openai_test"] = f"FAILED: {type(e).__name__}: {e}"

    # Check FAISS indices
    results["chunk_faiss_exists"] = (settings.chunk_faiss_dir / "index.faiss").exists()
    results["faq_faiss_exists"] = (settings.faq_faiss_dir / "index.faiss").exists()

    if "FAILED" in str(results.get("gemini_test")) or "FAILED" in str(results.get("openai_test")):
        results["status"] = "degraded"

    return results
